version: '3'

volumes:
  pg_data_prod:
  static_volume:
  media_volume:
services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_prod:/var/lib/postgresql/data
  backend:
    image: eniks1632/kittygram_backend:1.2
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media_volume:/app/media/
  frontend:
    env_file: .env
    image: eniks1632/kittygram_frontend:1.2
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    depends_on:
    - backend
    env_file: .env
    image: eniks1632/kittygram_gateway:1.2
    ports:
      - 9000:80
    volumes:
      - static_volume:/static/
      - media_volume:/app/media/
