version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    depends_on:
    - backend
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static/
      - media:/app/media/
  frontend:
    image: kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static/
  gateway:
    depends_on:
      - backend
    image: kittygram_gateway
    ports:
      - '9000:80'
    volumes:
      - static:/static/
      - media:/app/media/